package Entity;

public enum Posicion {
    PORTERO,
    DEFENSA_CENTRAL,
    LATERAL_DERECHO,
    LATERAL_IZQUIERDO,
    MEDIOCENTRO_DEFENSIVO,
    MEDIOCENTRO,
    MEDIOCENTRO_OFENSIVO,
    EXTREMO_DERECHO,
    EXTREMO_IZQUIERDO,
    DELANTERO_CENTRO,
    SEGUNDO_DELANTERO
}
